name: biomero-converter-env
channels:
 - conda-forge
 - defaults
dependencies:
 - python==3.12
 - numpy
 - zarr
 - ome-zarr
 - tifffile
 - imagecodecs
 - dask[array]
 - pip
 - pip:
   - ome-types==0.6.2
   - pyisyntax
   - openslide-python
   - openslide-bin
